// Variáveis de parceiros
const parceiros = {
  "Adriana Nogueira do Nascimento (POLO)": "Carteira 1",
  "Alcinete Silva Pereira (POLO)": "Carteira 1",
  "ALEX DAMASCENA DOS SANTOS (POLO)": "Carteira 1",
  "AMADEU CORDEIRO TEIXEIRA (POLO)": "Carteira 1",
  "ANDREA MARCIA DA SILVA MONTALVAO (POLO)": "Carteira 1",
  "ANTONIO ENIVALDO HONORIO DE SOUZA (POLO)": "Carteira 1",
  "ANTONIO PINHEIRO DE REZENDE (POLO)": "Carteira 1",
  "Antônio Rodolfo de Siqueira": "Carteira 1",
  "CARLANA DA SILVA ALFAIA (POLO)": "Carteira 1",
  "CLAUDIA MARIA DE SOUSA FREIRE (POLO)": "Carteira 1",
  "Clodoaldo Reis Azarias (POLO)": "Carteira 1",
  "Daiane Leandro Lima Pereira (POLO)": "Carteira 1",
  "Débora do Nascimento Teófilo": "Carteira 1",
  "DIEGO MUNHOZ FERREIRA (POLO)": "Carteira 1",
  "DILMA FERREIRA DE OLIVEIRA COLODEL (POLO)": "Carteira 1",
  "EDILEUZA MENDES SANTOS DE LIMA / ARTHUR MENDES DE LIMA (POLO)": "Carteira 1",
  "Eliane Barbosa Dantas (POLO)": "Carteira 1",
  "Elisa Oleide Dambrós Pereira": "Carteira 1",
  "FATIMA APARECIDA PERALTA (POLO)": "Carteira 1",
  "Flávio de Mello Lopes": "Carteira 1",
  "GABRIEL PINHEIRO RIBEIRO (POLO)": "Carteira 1",
  "GLENDA ALINE RODRIGUES MOREIRA (POLO)": "Carteira 1",
  "Iapeg Instituto de Apoio Pedagogico em Goiás": "Carteira 1",
  "IEDA ALVES PAIVA (POLO)": "Carteira 1",
  "ILIONI APARECIDA DE OLIVEIRA": "Carteira 1",
  "JADY SELVA DA SILVA ARAUJO (POLO)": "Carteira 1",
  "JAIME TELES DOS SANTOS (POLO)": "Carteira 1",
  "JOSE DONIZETE DE CASTRO (POLO)": "Carteira 1",
  "LEANDRO GERALDO DOS SANTOS (POLO)": "Carteira 1",
  "LEINE CLAUDIA RODRIGUES DE SOUZA (POLO)": "Carteira 1",
  "LENI DE MOURA BARROS (POLO)": "Carteira 1",
  "Letícia Cláudia Camargo Fargnoli (POLO)": "Carteira 1",
  "Liliane Gonçalves de Lima": "Carteira 1",
  "MARCOS DE SOUZA (POLO)": "Carteira 1",
  "MARIA LUIZA ALVES NETA (POLO)": "Carteira 1",
  "MARIO DE OLIVEIRA MARTINS (POLO)": "Carteira 1",
  "Med Vantagens Consultoria e Corretora de Seguros": "Carteira 1",
  "MONICA APARECIDA MARQUES (POLO)": "Carteira 1",
  "Nandara": "Carteira 1",
  "NELSON MANUEL CARVALHO SILVA LIMA": "Carteira 1",
  "NOEME ALVES DA COSTA MANZICO (POLO)": "Carteira 1",
  "RAIMUNDO FERREIRA RODRIGUES / HELORRAYNE (POLO)": "Carteira 1",
  "Roney Rabelo Felix": "Carteira 1",
  "Ronnyelle Pinto do Carmo (POLO)": "Carteira 1",
  "ROSANA DOS SANTOS CANAL (POLO)": "Carteira 1",
  "ROSEMERY ALVES SILVA (POLO)": "Carteira 1",
  "Thais de Paula e Silva (POLO)": "Carteira 1",
  "Tulio Vinicius Gomes Andrade (PARCEIRO)": "Carteira 1",
  "ULISSES BERNARDO GALVAO DE OLIVEIRA (POLO)": "Carteira 1",
  "WIRLEY MOREIRA DA SILVA (POLO)": "Carteira 1",
  "ALESSANDRO EUZEBIO BATISTA": "Carteira 2",
  "Altivo Ferreira Santana Neto (POLO)": "Carteira 2",
  "AMANDA MAGALHAES CARVALHO SILVA (POLO)": "Carteira 2",
  "AMARILIDES BATISTA PEREIRA": "Carteira 2",
  "Anderson Carlos Diniz Silva": "Carteira 2",
  "ANDRE SANTOS CARDOSO": "Carteira 2",
  "André Silva Prata": "Carteira 2",
  "ASEC ASSOCIAÇÃO EDUCACIONAL COMUNITARIA": "Carteira 2",
  "Cristovao Gomes Ribeiro": "Carteira 2",
  "Daniel Ferreira da Silva": "Carteira 2",
  "DENIZE SILVEIRA RIBEIRO (POLO)": "Carteira 2",
  "DIRCEU NOVAIS FERREIRA (POLO)": "Carteira 2",
  "Edson Fonseca dos Santos": "Carteira 2",
  "Eulalia Maria de Azevedo Resende (POLO)": "Carteira 2",
  "Francisco Rosiel de Freitas Silva": "Carteira 2",
  "GERSON LUIZ MOREIRA": "Carteira 2",
  "GISELE DE SOUZA ANACLETO (POLO)": "Carteira 2",
  "JOSENILDO MANOEL BARROS (POLO)": "Carteira 2",
  "Laurent Kifer Moreira": "Carteira 2",
  "LINEIA SOARES DA SILVA": "Carteira 2",
  "Marcos Rodrigo Leite": "Carteira 2",
  "MARGARETH DO ROSARIO R DE ALMEIDA PEREIRA (POLO)": "Carteira 2",
  "MARIA COLODIANO": "Carteira 2",
  "Maria do Socorro de Brito Siqueira Campos": "Carteira 2",
  "Maria Lucia de Araújo": "Carteira 2",
  "MARILENE ALVES PINHEIRO": "Carteira 2",
  "Meire Cristina de Oliveira Machado": "Carteira 2",
  "MICHELINA HENRIQUE DA ROCHA": "Carteira 2",
  "Nilton José de Pinho (POLO)": "Carteira 2",
  "PAULO HENRIQUE DA SILVA LEITAO (POLO)": "Carteira 2",
  "Rodrigo Guedes Dos Santos": "Carteira 2",
  "RV SERVIÇOS EDUCACIONAIS E COMERCIAIS EIRELI": "Carteira 2",
  "Sandra Maria Alves Barbosa Melo": "Carteira 2",
  "Selma Coelho": "Carteira 2",
  "Solange de Oliveira Bruneli": "Carteira 2",
  "Suely Lula Teodoro Martins": "Carteira 2",
  "Terezinha Lourenço": "Carteira 2",
  "Thiago Juan Lima Pereira / Nome Fantasia": "Carteira 2",
  "Urbano Rodrigues Azambuja": "Carteira 2",
  "Valdeglacia Pinheiro Dantas Domingos": "Carteira 2",
  "Vanderlei Alves de Macedo (POLO)": "Carteira 2",
  "Vitória Regia Pinto Sodré Gama": "Carteira 2",
  "Wagner da Silva Henriques": "Carteira 2",
  "Walaci Magnago": "Carteira 2",
  "WERIKA LILLIAN BATISTA NUNES": "Carteira 2",
  "WILHAN NASCIMENTO DE JESUS": "Carteira 2",
  "ADOLFO RAMOS MARQUES CENTURION": "Carteira 4",
  "ALDECIR GOMES DA SILVA": "Carteira 4",
  "ALESSANDRA TORRES FAGUNDES ALVES": "Carteira 4",
  "Aline Araujo": "Carteira 4",
  "ANA FLÁVIA SILVA BORGES COELHO": "Carteira 4",
  "ANA LÚCIA ALMEIDA ABRANCHES": "Carteira 4",
  "ANA LUIZA DE OLIVEIRA CASTRO (POLO)": "Carteira 4",
  "ANDRE ANTUNES DA MATA (PARCEIRO)": "Carteira 4",
  "ANDRE SOARES MENDES (PARCEIRO)": "Carteira 4",
  "ANTONIO LEONARDO ALVES DE SOUSA": "Carteira 4",
  "Antônio Marcos Cruz de Oliveira": "Carteira 4",
  "BIANCA SILVA (PARCEIRO)": "Carteira 4",
  "Bruna Daudt de Castro (PARCEIRO)": "Carteira 4",
  "Caio Carvalho Vieira Nascimento (PARCEIRO)": "Carteira 4",
  "CECILIA APARECIDA GHIROTTI (PARCEIRO)": "Carteira 4",
  "Cleber Alves de Souza": "Carteira 4",
  "CRISTIANE PACHECO BRAGA (PARCEIRO)": "Carteira 4",
  "DAIANA MAIA DE CASTRO MALVEIRA": "Carteira 4",
  "Daniel de Almeida Alves (PARCEIRO)": "Carteira 4",
  "DAVID WON HELDER FERREIRA DE MIRANDA SANTOS": "Carteira 4",
  "Deyvison Santos (PARCEIRO)": "Carteira 4",
  "DICEIA COSTA MOREIRA (POLO)": "Carteira 4",
  "Dirceia Cristina Silva Mendonça (PARCEIRO)": "Carteira 4",
  "Edilene Marilia de Miranda Rodrigues": "Carteira 4",
  "EVA MARIA BASTOS CERQUEIRA": "Carteira 4",
  "Evolue Consutoria Educacional Ltda. (PARCEIRO)": "Carteira 4",
  "FABIO BATISTA DA SILVA": "Carteira 4",
  "FABIO RODRIGUES DIAS": "Carteira 4",
  "Facprisma Faculdade de Ensino Superior Ltda": "Carteira 4",
  "FERNANDA CARLA SILVA BOHRER LOBOSCO (PARCEIRO)": "Carteira 4",
  "Francisca Vamária Pinheiro (PARCEIRO)": "Carteira 4",
  "Francisco das Chagas Lima Dos Santos Júnior": "Carteira 4",
  "FRANCISCO WILAME PEREIRA DE LIMA": "Carteira 4",
  "Francisdalva Malafaia Silva (PARCEIRO)": "Carteira 4",
  "FRANCISROBERT PEREIRA TEIXEIRA": "Carteira 4",
  "GILDAZIO MOREIRA SANTOS": "Carteira 4",
  "GISELE ROSSI LEONEL (PARCEIRO)": "Carteira 4",
  "GUILHERME AUGUSTO DIAS BALDO": "Carteira 4",
  "Gustavo Silva de Paiva Pereira": "Carteira 4",
  "GUSTAVO SOARES SANTOS (PARCEIRO)": "Carteira 4",
  "HELENA MARA MACHADO/ MARCIEL PEREIRA FELIX": "Carteira 4",
  "Integral Representações Ltda (POLO)": "Carteira 4",
  "ISRAEL BEZERRA PEREIRA": "Carteira 4",
  "Janice Queiroz de Almeida": "Carteira 4",
  "Jefferson Vitoriano Sena": "Carteira 4",
  "Jeova dos Santos": "Carteira 4",
  "JOAO PAULO DE TARSO MEMORIA": "Carteira 4",
  "JOÃO PEDRO GOMES DE MELO": "Carteira 4",
  "JOSE EDUARDO DA SILVA (PARCEIRO)": "Carteira 4",
  "Josiane Novais Vidal Costa": "Carteira 4",
  "Judite Vieira macedo": "Carteira 4",
  "Julio Cesar Santos Pereira": "Carteira 4",
  "KELLY CRISTINA SOUZA GONCALVES SANTOS": "Carteira 4",
  "KELLY CRISTINA SOUZA GONÇALVES SANTOS": "Carteira 4",
  "LETICIA BEZERRA LIMA": "Carteira 4",
  "Lilian Freitas Alves Martins": "Carteira 4",
  "Lindyberg Ferreira Reinaldo": "Carteira 4",
  "Linicassia Mesquita da Costa": "Carteira 4",
  "Luciane Cristina Araújo": "Carteira 4",
  "MARCIA CARVALHO FERREIRA": "Carteira 4",
  "MARCOS ANTONIO DE PAULA": "Carteira 4",
  "MARCOS JOSÉ PEREIRA BARROS (PARCEIRO)": "Carteira 4",
  "MARIA BATISTA ASSUNCAO SOUZA": "Carteira 4",
  "MARIA GORETE FRONTINO": "Carteira 4",
  "MARIA PAMELA BASTOS FERREIRA": "Carteira 4",
  "Mateus Cerqueira Anício Morais": "Carteira 4",
  "NATALIA DE SOUSA LOPES DE ALMEIDA": "Carteira 4",
  "PABLO HENRIQUE SOARES DE SA RIBANA (PARCEIRO)": "Carteira 4",
  "PATRICIA CARDOSO DE MENEZES (PARCEIRO)": "Carteira 4",
  "PATRICIA SALDANHA VASCONCELOS": "Carteira 4",
  "PAULA DE ESPINDOLA MARTINS ALBINO (PARCEIRO)": "Carteira 4",
  "Pedro Lucas Silva Fraga (PARCEIRO)": "Carteira 4",
  "PERFORMAR CONSULTORIA DE INOVACAO E ESTRATEGIA LTDA": "Carteira 4",
  "RAFAEL RODRIGUES DUQUE (PARCEIRO)": "Carteira 4",
  "RAFAELA APARECIDA RIBEIRO (PARCEIRO)": "Carteira 4",
  "RAIMUNDO DE CASTRO SOARES": "Carteira 4",
  "Raphael Ferreira de Souza": "Carteira 4",
  "RENATA TOSTA DA SILVA": "Carteira 4",
  "RICARDO FURTADO DE OLIVEIRA": "Carteira 4",
  "Rosanne Cavalcante Rodrigues de Souza": "Carteira 4",
  "RUBIVALDO RAMOS DOS SANTOS": "Carteira 4",
  "Sergio Ricardo Souza Pacheco": "Carteira 4",
  "Sionara Felix Trigueiro": "Carteira 4",
  "TERESA RAQUEL PIRES SOARES": "Carteira 4",
  "Thays Landazuri de Aguiar": "Carteira 4",
  "Thiago Britto França": "Carteira 4",
  "V2R DIGITAL LTDA": "Carteira 4",
  "VALDIR DA CUNHA": "Carteira 4",
  "Walef Kesse Coelho de Almeida": "Carteira 4",
  "WANESSA MARIA CARVALHO COSTA": "Carteira 4",
  "WILDSON FERREIRA COELHO": "Carteira 4",
  "ADELINE APARECIDA DO NASCIMENTO SILVA": "Carteira 5",
  "ADLINE DA SILVA REBIS": "Carteira 5",
  "Adriano Rodrigues Sena": "Carteira 5",
  "Alcimério Silvestre (Estúdio Lapa Produções Ltda )": "Carteira 5",
  "ALEFE DE OLIVEIRA BATISTA": "Carteira 5",
  "ALESSANDRA FERNANDES NOGUEIRA PAULO": "Carteira 5",
  "Alessandra Teixeira de Sá": "Carteira 5",
  "ALINE DARC SILVEIRA DOS SANTOS TEOFILO": "Carteira 5",
  "Aline Roberta Lima Nishimura Aiko": "Carteira 5",
  "Allef Henrique de Oliveira": "Carteira 5",
  "ANA PAULA DE MELO MEDEIROS": "Carteira 5",
  "Ana Paula de Melo Medeiros": "Carteira 5",
  "Ana Paula dos Santos": "Carteira 5",
  "ANDER CLEISON DA SILVA": "Carteira 5",
  "André Halley Maciel Ferreira": "Carteira 5",
  "André Lanna de Lima e Silva": "Carteira 5",
  "ANDRESA FERNANDA DE SOUZA SILVA": "Carteira 5",
  "Antonio Geraldo Esteves": "Carteira 5",
  "ANTONIO RICARDO SATURNINO DA SILVA": "Carteira 5",
  "Antonio Ricardo Saturnino da Silva": "Carteira 5",
  "Arthur Vieira Rocha": "Carteira 5",
  "BENEDITO JOSÉ DA SILVA": "Carteira 5",
  "Camaleon Educação e Marketing LTDA (Douglas Crivelli Rodrigues)":"Carteira 5",
  "CARLA ANASTACIO DA SILVA (PARCEIRO)": "Carteira 5",
  "Claudia cristina da silva": "Carteira 5",
  "Cláudia Cristina da Silva": "Carteira 5",
  "Cláudio Joaquim dos Santos Braga": "Carteira 5",
  "Cleiton Santos Guedes": "Carteira 5",
  "Cristina Pavani Couto": "Carteira 5",
  "Daciana Ferreira Pimentel": "Carteira 5",
  "Daniel Cairo de Sousa Costa": "Carteira 5",
  "DANIELA CRISTINA OLIVEIRA ANASTACIO": "Carteira 5",
  "DANUSA RODRIGUES ALCADES": "Carteira 5",
  "DARCILEI MACIEL SIMIONATTO (PARCEIRO)": "Carteira 5",
  "Dioney da Silva Lopes": "Carteira 5",
  "DIRCE APARECIDA FERREIRA MARQUES": "Carteira 5",
  "DIVINA ROSA PEREIRA DIAS": "Carteira 5",
  "Douglas Henrique de Oliveira Batista": "Carteira 5",
  "Ederbal Forest - Doutor Forest Organization": "Carteira 5",
  "EDERCI FRANCISCO DOS SANTOS": "Carteira 5",
  "ELAINE DE MENDONÇA POLICARPO MARINS": "Carteira 5",
  "Elaine de Oliveira Fontes": "Carteira 5",
  "ELEN SOUZA SANTANA": "Carteira 5",
  "Eliane Silvino da Silva": "Carteira 5",
  "Eliziomar Linhares Pontes": "Carteira 5",
  "EMANUELLE BRAZ MONTEIRO": "Carteira 5",
  "Erivaldo de Lima Silva": "Carteira 5",
  "Erivaldo de Lima Silva": "Carteira 5",
  "ERIVELTON MIRANDA LOPES": "Carteira 5",
  "Everton Fernando Ferreira Meira": "Carteira 5",
  "FERNANDA MACEDO BARBOSA": "Carteira 5",
  "Francisco Everardo Ferreira Lima (PARCEIRO)": "Carteira 5",
  "FRANCISCO HEDLER BARRETO DE LIMA MORAIS": "Carteira 5",
  "Francisco Rômulo Oliveira Magalhães": "Carteira 5",
  "Geverson Façanha da Silva": "Carteira 5",
  "Gilmar de Sousa Dias (PARCEIRO)": "Carteira 5",
  "Gleidison Rosado de Oliveira": "Carteira 5",
  "HELEN TATIANA ZANDA RIBEIRO": "Carteira 5",
  "IARA DE SOUSA": "Carteira 5",
  "IARA DE SOUSA": "Carteira 5",
  "Irani da Silva de Jesus": "Carteira 5",
  "Irlan Lopes da Silva": "Carteira 5",
  "Irlana Mendonça Lima": "Carteira 5",
  "Izadora Ribeiro da Silva": "Carteira 5",
  "IZAUL DE SOUZA TADEU": "Carteira 5",
  "J C GALVAO GOULART DE OLIVEIRA - NEGOCIOS IMOBILIARIOS": "Carteira 5",
  "Jailson da Silva Sacramento - whoisai education ltda": "Carteira 5",
  "JAMILE MAMBREU ISSE AZEVEDO": "Carteira 5",
  "Jean Jardim Jorge": "Carteira 5",
  "Jeancarlas Barbosa de Figueredo": "Carteira 5",
  "Jessyca Silva Mota da Silva": "Carteira 5",
  "JHONATAN DA COSTA LEITE PIMENTA": "Carteira 5",
  "João Carlos de Brito": "Carteira 5",
  "JOÃO CARLOS DE BRITO": "Carteira 5",
  "joão vitor dos santos da silva": "Carteira 5",
  "Jonathan Albuquerque - Centro Educacional Albuquerque": "Carteira 5",
  "Jorge Ferreira Figueiredo": "Carteira 5",
  "JOSE ANTONIO MORAES DE OLIVEIRA": "Carteira 5",
  "José Hilário Dias Nero": "Carteira 5",
  "JOSE VANDERLEI RODRIGUES MOURA": "Carteira 5",
  "JOSICLEIA GOMES NUNES": "Carteira 5",
  "Jozian Miranda Chaves": "Carteira 5",
  "Juliana Ferreira Rimes da Silva": "Carteira 5",
  "Karen Dorneles Rodilha": "Carteira 5",
  "Kelly Cristina Marinho Umbelino": "Carteira 5",
  "Kelvin Kyoshi Kamimura": "Carteira 5",
  "LARISSA AZEVEDO RESENDE": "Carteira 5",
  "Larissa Dantas de Torquato Costa": "Carteira 5",
  "LEANDRO BIANCHINI GARCIA": "Carteira 5",
  "LELIO FAVACHO BRAGA": "Carteira 5",
  "LEONARDO FLAUSINO ARAUJO SILVA": "Carteira 5",
  "Leonardo Flausino Araujo Silva": "Carteira 5",
  "LEYDE IZABEL FERNANDES LEMOS REIS": "Carteira 5",
  "LILIAN DE ARAUJO SILVEIRA": "Carteira 5",
  "LIMIAR VAREJO E SERVIÇOS LTDA": "Carteira 5",
  "Lisiane Magalhães Fernandes Vicente": "Carteira 5",
  "Lucas Gonçalves de Oliveira Alves (PARCEIRO)": "Carteira 5",
  "Lucellia Luiza Peixoto de Paula": "Carteira 5",
  "Luciana Aparecida Moreira": "Carteira 5",
  "Luciane dos Santos Situba (PARCEIRO)": "Carteira 5",
  "LUIS DE FRANÇA CAMBOIM NETO": "Carteira 5",
  "LUIZ CARLOS SILVERIO DOS SANTOS": "Carteira 5",
  "LUIZ VELOSO LEMOS JUNIOR": "Carteira 5",
  "Magna Cristina Costa Silva Rodrigues": "Carteira 5",
  "Manoel Messias Braga França - Jeferson": "Carteira 5",
  "MANOEL NETO DE SOUSA": "Carteira 5",
  "Marcelino Teixeira Santos": "Carteira 5",
  "Marcelly Teixeira Tinoco": "Carteira 5",
  "Marcia Cristina da Mota Sales": "Carteira 5",
  "MARCIA CRISTINA DA SILVA DIAS": "Carteira 5",
  "Marciel Alan Freitas de Castro": "Carteira 5",
  "Marcio Roberto Bringhenti": "Carteira 5",
  "Marco Túlio de Pinho Tavares": "Carteira 5",
  "Marcos Henrique Martins de Andrade": "Carteira 5",
  "Marcos Kayro Lopes Pontes": "Carteira 5",
  "MARIA APARECIDA RODRIGUES ASSUNCAO": "Carteira 5",
  "MARIA HELENA KUCZKA": "Carteira 5",
  "MARIA PIEDADE COSTA": "Carteira 5",
  "Maria Piedade Costa": "Carteira 5",
  "Maria Themis de Siqueira Campos Moura": "Carteira 5",
  "MARTA PIRES FERREIRA RIBEIRO": "Carteira 5",
  "Mateus Duarte Cal": "Carteira 5",
  "Mayhara Jordanna Lira Da Costa": "Carteira 5",
  "MICHEL FRANK NASCIMENTO RODRIGUES": "Carteira 5",
  "Mike Dias Reis": "Carteira 5",
  "Mirian Carla da Silva": "Carteira 5",
  "Nilza Lopes Barra": "Carteira 5",
  "Oráculo cursos Ltda": "Carteira 5",
  "PABLO DOS SANTOS SILVARES": "Carteira 5",
  "PAULO FERNANDES PERES": "Carteira 5",
  "Raiane Beatriz Romolo": "Carteira 5",
  "Raul Rodrigues Vieira (PARCEIRO)": "Carteira 5",
  "REGINA ELIZABETH COSTA DE ALMEIDA": "Carteira 5",
  "Renata Martins Bispo": "Carteira 5",
  "RIANE LEANDRO DE SOUZA": "Carteira 5",
  "Riane Leandro de Souza": "Carteira 5",
  "RICARDO RODRIGUES PEREIRA": "Carteira 5",
  "Riviane Oliveira dos Santos": "Carteira 5",
  "Robson Cláudio da Silva": "Carteira 5",
  "ROMONIQUE GLEYSON FERREIRA MATOS": "Carteira 5",
  "Rosimar Soares Mollendorff - Creche Broto Novo Ltda": "Carteira 5",
  "Rozane Simone Fonseca Armelin da Silva": "Carteira 5",
  "Samara Ribeiro de Araujo Ferreira": "Carteira 5",
  "Samara Ribeiro De Araujo Ferreira": "Carteira 5",
  "Sandra Bengozi de Carvalho": "Carteira 5",
  "SILVANIA CURTY DO COUTO/JEIVES PERES": "Carteira 5",
  "Simone dos Santos Severino Campista": "Carteira 5",
  "SIVALDO JOSÉ RIBEIRO AMORIM": "Carteira 5",
  "SOLANGE APARECIDA LOPES": "Carteira 5",
  "Suênia Kercia dos Santos Sales": "Carteira 5",
  "T R C ROCHA - PROMOÇÃO E DIVULGAÇÃO": "Carteira 5",
  "TANIA FERREIRA DE ALMEIDA HOLUB": "Carteira 5",
  "Tatiane Regina Lopes Aguilheira Cunha": "Carteira 5",
  "Telma Regina de Melo Molina Pedroso": "Carteira 5",
  "Telma Regina de Melo Molina Pedroso": "Carteira 5",
  "TERCIO CARLOS XAVIER": "Carteira 5",
  "Tiago Rodrigues Santos": "Carteira 5",
  "Ulisses Nyland": "Carteira 5",
  "VALTER DOS ANJOS SOUZA (PARCEIRO)": "Carteira 5",
  "VERONICA TEIXEIRA DE SOUZA ARAUJO": "Carteira 5",
  "WALMIR DOS SANTOS TEIXEIRA / ROSELIA": "Carteira 5",
  "Walter Monteiro": "Carteira 5",
  "WANCARLOS JOSE MUELLER NETO": "Carteira 5",
  "Wancarlos José Mueller Neto": "Carteira 5",
  "WARLEY EMANUEL DE OLIVEIRA": "Carteira 5",
  "WEYDER SOUZA VIEIRA (PARCEIRO)": "Carteira 5",
  "ALESSANDRO FAUSTINO BRUSCHI": "Carteira 6",
  "AUDREY RODRIGUES DOS SANTOS DIAS": "Carteira 6",
  "DANUBIA KELLY NUNES BRUSCHI (PARCEIRO)": "Carteira 6",
  "Marcelo Albuquerque Sarmento": "Carteira 6",
  "MARCIENI ALVES VIEIRA": "Carteira 6",
  "PATRICIA VESZ": "Carteira 6",
  "Leonardo da Silva Melo": "NOVATOS",
  "Sistêmica Educação Ltda": "NOVATOS",
  "Wânia de Lima Ferreira Medeiros Silva": "NOVATOS",
  "A.M PENA LTDA": "NOVATOS",
  "Adailson Tozzi Junior": "NOVATOS",
  "Adenilton Pezzott": "NOVATOS",
  "Adna Karen Mendonça de Medeiros Silva": "NOVATOS",
  "Adriana Paloschi": "NOVATOS",
  "ALCANCE SUPERIOR EDUCACIONAL EIRELI": "NOVATOS",
  "Angelita Aparecida Azevedo Freitas": "NOVATOS",
  "Carina Zanatta Cervelin": "NOVATOS",
  "CARLOS MAGNO DOS SANTOS": "NOVATOS",
  "Carlos Roberto Ribeiro": "NOVATOS",
  "Caroline de Sousa Lopes Heiden": "NOVATOS",
  "Cesar Augusto Ferreira": "NOVATOS",
  "Clara Adriane Campos dos Santos": "NOVATOS",
  "Cognitiva Psicologia Clinica e Organizacional": "NOVATOS",
  "Cristiane Cardoso Bloemer": "NOVATOS",
  "Cristina Maria Silva Chaves Carvalho": "NOVATOS",
  "Daniela Santos Alves de Lima": "NOVATOS",
  "Dayeve Sales de Oliveira": "NOVATOS",
  "DIEGO BORGES DE OLIVEIRA": "NOVATOS",
  "Edgar Campos Neto": "NOVATOS",
  "Edney Agostinho de Castro": "NOVATOS",
  "Eleandro Soares de Freitas": "NOVATOS",
  "ESCOLA TECNICA MOTA & MOTA LTDA": "NOVATOS",
  "Espaço Pedagógico Somar": "NOVATOS",
  "EVANDRO LUIZ MAURICIO 16235731817": "NOVATOS",
  "Faculdade Evangélica Educacional Ltda.": "NOVATOS",
  "Fernanda Henrique de Almeida": "NOVATOS",
  "Filipius da Costa Correia da Silva": "NOVATOS",
  "Flavia Aparecida Cardoso Souza Duarte": "NOVATOS",
  "Francisco Cirineudo Pereira": "NOVATOS",
  "Herbet Carneiro Frota": "NOVATOS",
  "Isabela Fernandes Januario": "NOVATOS",
  "Jenner de Medeiros Fernandes": "NOVATOS",
  "Jhon Kelvys Araujo Campos": "NOVATOS",
  "JOÃO MORENO CLARES - MC9 COMERCIO E SERVICOS LTDA": "NOVATOS",
  "JONATAS NASCIMENTO SILVA": "NOVATOS",
  "José Reginaldo Santiago da Silva": "NOVATOS",
  "Josue Silva Sousa": "NOVATOS",
  "Juliana Paulino Ximenes": "NOVATOS",
  "Juliano Vitor Serafim": "NOVATOS",
  "Laiza Eduarda Souza da Luz": "NOVATOS",
  "Luciano de Carvalho Lourenço": "NOVATOS",
  "Márcia Beatriz Maciel de Lima": "NOVATOS",
  "Marcio Anderson Sousa Nunes": "NOVATOS",
  "Marcio Gevergi das Graças": "NOVATOS",
  "MARCOS ROBERTO DA ROCHA SOARES": "NOVATOS",
  "Marcos Vinicius de Souza": "NOVATOS",
  "Maressa Cristina Ferreira Pereira": "NOVATOS",
  "Michele Morais Cavalcante": "NOVATOS",
  "Nivalda Maria da Silva Milagre": "NOVATOS",
  "OKURA E FILHO PUBLICIDADE LTDA": "NOVATOS",
  "Osmar Pereira Trigueiro Júnior": "NOVATOS",
  "Paulo Cesar Tomaz": "NOVATOS",
  "PAULO HENRIQUE PEREIRA DOBBINS": "NOVATOS",
  "PEDRO MARTINS MACHADO": "NOVATOS",
  "Reginaldo Raimundo de Oliveira": "NOVATOS",
  "Rodrigo de Andrades Cabral": "NOVATOS",
  "Rosana Aparecida Pires Menezes": "NOVATOS",
  "Rute Manuela Vieira Piva": "NOVATOS",
  "Samuel Oliveira Abrantes": "NOVATOS",
  "Santana de Jesus Miranda Melo": "NOVATOS",
  "Siderlania Lira da Silva": "NOVATOS",
  "SPACE GAMER ESCOLA DE PROGRAMAÇÃO": "NOVATOS",
  "Stael Marlei de Souza e Silva": "NOVATOS",
  "Thailine Fortes Cecarechi Pontes": "NOVATOS",
  "Thaís Sthephany de Paiva Matos": "NOVATOS",
  "TONY EMMANUEL PRADO LIMA": "NOVATOS",
  "Valdemiro Antunes": "NOVATOS",
  "Valdo José Ananias de Oliveira": "NOVATOS",
  "Valéria Fernandes Alves": "NOVATOS",
  "Vânia Pereira de Souza (ETEC)": "NOVATOS",
  "W M Batista Faria Consultoria e Treinamento": "NOVATOS",
  "Yuri Medeiros da Silva Santos": "NOVATOS",
  // Adicione mais parceiros aqui
};
//Variáveis de carteiras
const carteiras = {
  "Carteira 1": "+553175211620",
  "Carteira 2": "+553175600226",
  "Carteira 4": "+553175273233",
  "Carteira 5": "+553193680179",
  "Carteira 6": "+553175600175",
  "NOVATOS": "+553182379090",
};
// Variáveis do modal
const modal = document.getElementById("consultor-modal");
const abrirModal = document.getElementById("abrir-modal");
const nomeInput = document.getElementById("nome-parceiro");
const listaAuto = document.getElementById("autocomplete-list");
const contatoSection = document.getElementById("contato-section");
const btnWhatsapp = document.getElementById("btn-whatsapp");
// Evento de abertura do modal
abrirModal.addEventListener("click", (e) => {
  e.preventDefault();
  modal.classList.remove("hidden");
  nomeInput.value = "";
  listaAuto.innerHTML = "";
  listaAuto.classList.add("hidden");
  contatoSection.classList.add("hidden");
});
// Evento de fechamento do modal
function fecharModal() {
  modal.classList.add("hidden");
}
// Evento de Autocomplete
nomeInput.addEventListener("input", function () {
  const texto = this.value.toLowerCase();
  listaAuto.innerHTML = "";
  if (texto.length === 0) {
    listaAuto.classList.add("hidden");
    return;
  }

  const sugestoes = Object.keys(parceiros).filter((nome) =>
    nome.toLowerCase().includes(texto)
  );
  if (sugestoes.length > 0) {
    listaAuto.classList.remove("hidden");
    sugestoes.forEach((nome) => {
      const item = document.createElement("li");
      item.textContent = nome;
      item.classList = "cursor-pointer px-3 py-2 hover:bg-purple-100";
      item.addEventListener("click", () => {
        nomeInput.value = nome;
        listaAuto.innerHTML = "";
        listaAuto.classList.add("hidden");
        mostrarContato(nome);
      });
      listaAuto.appendChild(item);
    });
  } else {
    listaAuto.classList.add("hidden");
  }
});
// Função para mostrar o contato
function mostrarContato(nome) {
  const carteira = parceiros[nome];
  if (carteira && carteiras[carteira]) {
    const numero = carteiras[carteira];
    btnWhatsapp.href = `https://wa.me/${numero}`;
    contatoSection.classList.remove("hidden");
  }
}
